Vagrant.configure(2) do |config|
	#fetching the ubuntu 14.04 64bit Desktop base-box from box-cutter(https://atlas.hashicorp.com/boxcutter) 
   config.vm.box = "box-cutter/ubuntu1404-desktop"
   config.vm.provider "virtualbox" do |vb| 
	#setting to render graphical user interface instead of command line interface 
     vb.gui = true  
	#setting default memory to 2048
     vb.memory = "2048"
	#setting vm name
     vb.name = "craven_ynallab_radar"

   end

   config.vm.provision "shell", inline: <<-SHELL
	#adding offical Oracle java repository
	 add-apt-repository -y ppa:webupd8team/java
	#updating repository index to reflect the new addition
	 apt-get update
	#accepting oracle license agreement
	echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
	#installing Oracle Java 8
	apt-get install -y oracle-java8-installer
	#Setting JAVA_HOME environment variable
	export JAVA_HOME=/usr/lib/jvm/java-8-oracle
	source /etc/environment
	#installing g++ to compile c++ files.
	apt-get install -y build-essential
	#Changing current directory to Desktop
	cd Desktop
	#Downloading 64bit eclipse for C/C++ developers from Pennsylvania State University mirrior
	wget "http://carroll.aset.psu.edu/pub/eclipse/technology/epp/downloads/release/indigo/SR2/eclipse-cpp-indigo-SR2-incubation-linux-gtk-x86_64.tar.gz"
	#extracting the downloaded eclipse tar file
    	tar zxf eclipse-cpp-indigo-SR2-incubation-linux-gtk-x86_64.tar.gz
	#Deleting the eclispse tar file after extraction
    	rm eclipse-cpp-indigo-SR2-incubation-linux-gtk-x86_64.tar.gz
	#Changing the folder ownership from root to vagrant user so that vagrant user can run eclipse after logging into vm.  
	chown -R vagrant: eclipse
   SHELL
end

