Vagrant.configure(2) do |config|
	#fetching the ubuntu 14.04 64bit Desktop base-box from box-cutter(https://atlas.hashicorp.com/boxcutter) 
   config.vm.box = "box-cutter/ubuntu1404-desktop"
   config.vm.provider "virtualbox" do |vb| 
	#setting to render graphical user interface instead of command line interface 
     vb.gui = true  
	#setting default memory to 2048
     vb.memory = "2048"
	#setting vm name
     vb.name = "craven_ynallab_radar"

   end

   config.vm.provision "shell", inline: <<-SHELL
	#adding offical Oracle java repository
	 add-apt-repository -y ppa:webupd8team/java
	#updating repository index to reflect the new addition
	 apt-get update
	#accepting oracle license agreement
	echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
	#installing Oracle Java 8
	apt-get install -y oracle-java8-installer
	#Setting JAVA_HOME environment variable
	export JAVA_HOME=/usr/lib/jvm/java-8-oracle
	source /etc/environment
	#installing g++ to compile c++ files.
	apt-get install -y build-essential
	#Changing current directory to Desktop
	cd Desktop
	#Downloading eclipse with preinstalled plugin and workspace from google drive shared folder
	wget "https://googledrive.com/host/0B-kwoOMu6poEXzNGbnI3Mk5VY1E/eclipse.tar.gz"
	#extracting the downloaded eclipse tar file
    tar zxvf radar-eclipse.tar.gz
	#Deleting the eclispse tar file after extraction
    rm radar-eclipse.tar.gz
	# Copy readme, installation, licenses, how-to video links to vm desktop
	wget https://github.com/SoftwareEngineeringToolDemos/ICSE-2013-RADAR/raw/master/build-vm/vm-contents/License.txt
	wget https://github.com/SoftwareEngineeringToolDemos/ICSE-2013-RADAR/raw/master/build-vm/vm-contents/Readme.txt
	wget https://github.com/SoftwareEngineeringToolDemos/ICSE-2013-RADAR/raw/master/build-vm/vm-contents/installation.txt
	wget https://github.com/SoftwareEngineeringToolDemos/ICSE-2013-RADAR/raw/master/build-vm/vm-contents/Youtube_demo_link.txt
	wget https://github.com/SoftwareEngineeringToolDemos/ICSE-2013-RADAR/raw/master/build-vm/vm-contents/Youtube_%20Radar-Demo_Video.desktop
	wget https://github.com/SoftwareEngineeringToolDemos/ICSE-2013-RADAR/raw/master/build-vm/vm-contents/eclipse.desktop
	wget https://github.com/SoftwareEngineeringToolDemos/ICSE-2013-RADAR/raw/master/build-vm/vm-contents/login_desktop.sh
	wget https://github.com/SoftwareEngineeringToolDemos/ICSE-2013-RADAR/raw/master/build-vm/vm-contents/login_desktop.sh.desktop
	#Changing the files on Desktop ownership from root to vagrant user so that vagrant user can run eclipse after logging into vm.  
	chown -R vagrant: *
	chmod -R 777 *
	
	# Add Eclipse to startup applications
	mkdir "/home/vagrant/.config/autostart"
	cp eclipse.desktop /home/vagrant/.config/autostart/eclipse.desktop
	
	# Install Adobe Flash Player plugin to view youtube videos
	apt-get install flashplugin-installer 
	
	# Remove unnecessary launcher applications
	rm -f "/usr/share/applications/ubuntu-amazon-default.desktop"
	rm -f "/usr/share/applications/libreoffice-calc.desktop"
	rm -f "/usr/share/applications/libreoffice-writer.desktop"
	rm -f "/usr/share/applications/libreoffice-impress.desktop"
	rm -f "/usr/share/applications/ubuntu-software-center.desktop"
	# Disable screen lockout
	mv /home/vagrant/Desktop/login_desktop.sh /home/vagrant/login_desktop.sh
	update-desktop-database
	cp /home/vagrant/Desktop/login_desktop.sh.desktop /etc/xdg/autostart/login_desktop.sh.desktop
	rm /home/vagrant/Desktop/login_desktop.sh.desktop
	# Reboot the VM
	sudo reboot
	SHELL
end
